name: Load ENV_FILE_DEV Secret
on:
  workflow_dispatch:

jobs:
  load-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Write .env file
        run: |
          cat << 'EOF' > .env
          ${{ secrets.ENV_FILE_DEV }}
          EOF
          
      - name: Verify .env file was created
        run: |
          echo "=== .env file contents ==="
          cat .env
          echo "=== End of .env file ==="
          echo "File size: $(wc -c < .env) bytes"
          
      - name: Export env variables from .env
        run: |
          set -o allexport
          source .env
          set +o allexport
          env | grep -E '^(SECRET_KEY|DEBUG|EMAIL_HOST_USER)='
          
      - name: Use environment variables
        run: |
          source .env
          echo "SECRET_KEY is: $SECRET_KEY"
          echo "DEBUG is: $DEBUG"
          echo "EMAIL_HOST_USER is: $EMAIL_HOST_USER"
