# name: SonarCloud analysis

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
#   workflow_dispatch:

# permissions:
#   pull-requests: read # allows SonarCloud to decorate PRs with analysis results

# jobs:
#   Analysis:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Analyze with SonarCloud
#         uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
#         with:
#           args:
#             -Dsonar.projectKey=sharan12221_Backend
#             -Dsonar.organization=sharan12221
#             -Dsonar.verbose=true
#           projectBaseDir: .


name: CI/CD for Node.js with SonarCloud and Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: devLen
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build-test-analyze-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args:
            -Dsonar.projectKey=sharan12221_Backend
            -Dsonar.organization=sharan12221
            -Dsonar.verbose=true
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Zip app for deployment
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: devLen
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app.zip
